### ISSUE TITLE
TODO list in the backend

### ISSUE THREAD

**Issue by zroger49** [racelandshop/camera_dashboard_raceland#2]
- [x] Fix the bug where the cameras added to not have feed
- [ ] Delete cameras (Make sure the in .storage are deleted as well)
- [ ] Edit camera information. (delete + add camera?)
- [ ] Better communication between backed and fronted (for example, don't show frontend data until are tasks in the backend are completed
